# Generated by Django 5.1 on 2025-01-03 15:48

import backend.apps.chat.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('task_id', models.CharField(default=backend.apps.chat.models.generate_uuid, editable=False, help_text='Message task id')),
                ('question', models.CharField(help_text="User's question", max_length=500)),
                ('optimized_question', models.CharField(blank=True, help_text='Optimized question', max_length=500, null=True)),
                ('received_sql_list', models.JSONField(default=list, help_text='Generated SQL list by AI', null=True)),
                ('valid_sql', models.CharField(blank=True, help_text='Valid SQL', max_length=2000, null=True)),
                ('query_result', models.JSONField(default=list, help_text='SQL execution result', null=True)),
                ('answer', models.JSONField(default=dict, help_text='The final answer presented to the user', null=True)),
                ('completed_at', models.DateTimeField(help_text='The time when the answer is completed', null=True)),
                ('step_times', models.JSONField(default=dict, help_text='Time record for each step', null=True)),
                ('is_cancelled', models.BooleanField(default=False, help_text='Whether the message is cancelled')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
