# Generated by Django 5.1 on 2025-01-03 15:48

import backend.apps.application.models
import oauth2_provider.generators
import oauth2_provider.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated')),
                ('post_logout_redirect_uris', models.TextField(blank=True, default='', help_text='Allowed Post Logout URIs list, space separated')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], max_length=32)),
                ('client_secret', oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Hashed on Save. Copy it now if this is a new secret.', max_length=255)),
                ('hash_client_secret', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('algorithm', models.CharField(blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5)),
                ('allowed_origins', models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(help_text='Application description', verbose_name='Description')),
                ('database_configuration', models.JSONField(help_text='Database configuration information for app', verbose_name='Database Configuration')),
                ('agent_configuration', models.JSONField(default=backend.apps.application.models._get_default_agent_configuration, help_text='Agent configuration information for app', verbose_name='Agent Configuration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDatabaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('document_name', models.CharField(max_length=128, verbose_name='Document name')),
                ('document_path', models.CharField(max_length=256, verbose_name='Document file path')),
                ('content_type', models.CharField(max_length=128, verbose_name='Content type')),
                ('document_size', models.IntegerField(verbose_name='Document file size')),
                ('token_count', models.IntegerField(blank=True, null=True, verbose_name='Document token count')),
                ('character_count', models.IntegerField(blank=True, null=True, verbose_name='Document character count')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question_clean_prompt', models.TextField(blank=True, null=True, verbose_name='Question clean prompt')),
                ('column_comment_prompt', models.TextField(blank=True, null=True, verbose_name='Column comment prompt')),
                ('question_builder_prompt', models.TextField(blank=True, null=True, verbose_name='Question builder prompt')),
                ('schema_rag_prompt', models.TextField(blank=True, null=True, verbose_name='Retrieve schema  prompt')),
                ('sql_generator_prompt', models.TextField(blank=True, null=True, verbose_name='SQL generator prompt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationSuggestedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question', models.CharField(help_text='A suggested question to be displayed on the homepage', max_length=1024, verbose_name='Suggested Question')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which questions should be displayed', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Application Suggested Question',
                'verbose_name_plural': 'Application Suggested Questions',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='Table Name')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Comment')),
                ('original_ai_comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Original AI comment')),
                ('ai_comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='AI comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationTableColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, verbose_name='Column Name')),
                ('key', models.CharField(max_length=16, verbose_name='Column Key')),
                ('type', models.CharField(max_length=32, verbose_name='Column Data Type')),
                ('default', models.JSONField(blank=True, null=True, verbose_name='Default')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Comment')),
                ('nullable', models.CharField(blank=True, default='YES', null=True, verbose_name='Nullable')),
                ('original_ai_comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Original AI comment')),
                ('ai_comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='AI comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FineTuningExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question', models.CharField(max_length=1024, verbose_name='question')),
                ('sql', models.CharField(max_length=1024, verbose_name='sql')),
            ],
        ),
        migrations.CreateModel(
            name='FineTuningModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('model_name', models.CharField(max_length=256, verbose_name='model_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
